### ISSUE TITLE
[Bug]无法加载专栏

### ISSUE THREAD

**Issue by oblessnoob** [MotooriKashin/Bilibili-Old#281]
**问题详情**
点击专栏之后标题栏一瞬间会出现一下专栏的标题，然后就变回网址并且卡住不动，页面空白。
关闭脚本后恢复正常。视频页无此问题

**复现步骤**
1. 点击专栏

**相关截图**
可以的话，提供一下截图，最好是控制台报错截图

read.js:138

Uncaught (in promise) TypeError: Cannot set properties of null (setting 'innerHTML')
    at Read.origin (read.js:138:65)
    at Read.tag (read.js:118:18)
    at Read.body (read.js:108:18)
    at Read.head (read.js:101:18)
    at Read.upinfo (read.js:87:18)
    at Read.bars (read.js:77:18)
    at Read.getIniState (read.js:67:18)

section.js:39

Uncaught TypeError: Cannot read properties of null (reading 'classList')
    at eval (section.js:39:38)
    at eval (units.js:179:17)

**运行环境**
 - 操作系统：Windows10 1909
 - 浏览器：Google Chrome 102.0.4977.0
 - 脚本管理器：Tampermonkey 4.16

**补充内容**
其他补充内容。

**Comment by MotooriKashin** [comment]
感谢反馈，已修复
